//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorLogger.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Generator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Generator()
        {
            this.GeneratorLogs = new HashSet<GeneratorLog>();
        }
    
        public long Id { get; set; }
        public string GeneratorName { get; set; }
        public string Latitude { get; set; }
        public string longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneratorLog> GeneratorLogs { get; set; }
    }
}
