//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorLogger.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratorLog
    {
        public long Id { get; set; }
        public Nullable<int> Temprature { get; set; }
        public Nullable<long> FK_GeneratorId { get; set; }
        public Nullable<System.DateTime> Logging_date { get; set; }
    
        public virtual Generator Generator { get; set; }
    }
}
